# Python Turtle:

In [3]:
# Changing Line Color
import turtle
t = turtle.Turtle()
t.pencolor("blue")
t.speed(100)

for i in range(50):
    t.forward(100)
    t.left(123)

t.pencolor("red")
for i in range(100):
    t.forward(100)
    t.left(123)
turtle.done()

In [9]:
# Sqaure of sqaures
import turtle
t = turtle.Turtle()
t.color("red")

def sqaure(size):
    for i in range(4):
        t.forward(size)
        t.left(90)
sqaure(146)
sqaure(126)
sqaure(96)
sqaure(76)
sqaure(56)
sqaure(36)
sqaure(16)

# Python Statistics Module:
- You can calculate mathematical statistics of numerical data
- Mean
- Median
- Mode
- Varience

In [10]:
import statistics as st
l = list(range(1,21))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [12]:
# Mean
print(st.mean(l))
print(sum(l)/len(l))

10.5
10.5


In [13]:
# Median - returns middle value of numerical data
print(st.median([1,2,3,4,5]))

3


In [14]:
# Mode - returns the most commom data point 
print(st.mode([2,5,2,2,5,4,76,6,6,4,3,]))

2


In [15]:
# Varience-standard deviation
print(st.variance(l))

35.0


# Random Module:
- used to get random numbers


In [3]:
# Random method
import random as rd
rd.random()

0.7052937892093556

In [8]:
# randint() - returns a random integer between specified integers
print(rd.randint(1,11))
print(rd.randint(1,100))

2
53


In [15]:
# randrange() - returns a randomly selected element from range created
print(rd.randrange(1,10))
print(rd.randrange(1,10,2))
print(rd.randrange(1,100,10))

6
3
31


In [23]:
# Choice -
l = [1,2,3,4,5]
print(rd.choice(l))
print(rd.choices(l,k = 6))

3
[2, 2, 5, 5, 1, 5]


In [25]:
# Shuffle
l = [1,2,3,4,5]
rd.shuffle(l)
print(l)

[1, 4, 3, 5, 2]


# Numpy Module:
- Numpy library is used for working with arrays
- Numpy stands for numerical Python

In [27]:
import numpy as np
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [28]:
l = list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [29]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Dimension in Arrays

In [30]:
# 1 - D
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [31]:
# 2 -D
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [32]:
# 3 - D
arr2 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr2)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
